
name: Greeter

on:
  push:
    branches:
      - master
  schedule: 
    - cron: '5 * * * *'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/ekson
      with:
        input: boff
    - name: Greetings
