
name: Greeter

on:
  push:
    branches:
      - main
  schedule: 
    - cron: '5 * * * *'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: input
      uses: ./.github/actions/ekson
      with:
        input: boff
      name: Greetings
    - run: echo $RANDOM_NUMBER ; if [ $RANDOM_NUMBER -ge 10 ]; then echo GE10 ; else echo LE10 ; fi
      shell: bash
      env:
        RANDOM_NUMBER: ${{ steps.input.outputs.random-number }}
