name: Protected envs and stages

on:
  push:
    branches:
      - master


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4

      - name: Build or simulate building
        run: sleep 5

      - name: Finish building
        run: echo "Build completed successfully"

  # Chain the next job to the previous one and make it deploy
  # to different environments with manual approvals
  deploy_dev:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: deploy
        run: echo dev
  deploy_acc:
    needs: deploy_dev
    runs-on: ubuntu-latest
    environment: acc
    steps:
      - name: deploy
        run: echo acc
  deploy_prod:
    needs: deploy_acc
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: deploy
        run: echo prod